# Generated by Django 4.1.5 on 2023-03-06 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recuriter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('password', models.CharField(max_length=24)),
                ('email_address', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=24)),
                ('companyname', models.CharField(max_length=24)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('password', models.CharField(max_length=24)),
                ('email_address', models.CharField(max_length=24)),
                ('phone', models.CharField(max_length=24)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=24)),
                ('companyname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.recuriter')),
            ],
        ),
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Application_Status', models.CharField(choices=[('Applied', 'Applied'), ('Under Review', 'Under Review'), ('Rejected', 'Rejected'), ('Selected', 'Selected')], max_length=24)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.recuriter')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.user')),
            ],
        ),
    ]
