# Generated by Django 4.1.5 on 2023-03-06 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrations',
            name='role',
        ),
    ]
