# Generated by Django 4.1.5 on 2023-03-06 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0003_registrations_jobrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='Jobrole',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='Jobs.role'),
        ),
    ]
